## template: jinja
#cloud-config
# yamllint disable rule:document-start rule:line-length
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
write_files:
runcmd:
  # install docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - while ! docker --version; do echo trying again&sleep 1; done
  # run webapp
  - docker run -d --net=host --restart=always --name webapp -p 80:80 -e F5DEMO_APP=${f5demo_app} -e F5DEMO_NODENAME='${f5demo_nodename}' -e F5DEMO_COLOR=${f5demo_color} f5devcentral/f5-demo-httpd:nginx
  # run diagnostics
  - docker run -d --net=host --restart=always --name container-demo-runner -p 8080:8080 -p 5001:5001 -p 11111:11111 jgruberf5/container-demo-runner:latest
